# Generated by Django 5.0.7 on 2024-08-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(max_length=100, verbose_name='شماره تماس')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نام')),
            ],
        ),
    ]
