# Generated by Django 5.0.7 on 2024-08-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'مشترکین ما', 'verbose_name_plural': 'مشترکین ما'},
        ),
    ]
