# Generated by Django 5.0.7 on 2024-08-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(max_length=3, verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='family',
            field=models.CharField(max_length=100, verbose_name='نشان'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='job',
            field=models.CharField(max_length=100, verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(default='', verbose_name='اسلاگ'),
        ),
    ]
