# Generated by Django 5.0.7 on 2024-08-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_age_alter_customer_family_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'مشتریان', 'verbose_name_plural': 'مشتری'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(verbose_name='سن'),
        ),
    ]
