# Generated by Django 5.0.7 on 2024-08-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productinfo_alter_product_slug_product_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='size',
            field=models.CharField(max_length=100, verbose_name='سایز محصول'),
        ),
    ]
