# Generated by Django 5.0.7 on 2024-08-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productinfo_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='slug',
        ),
    ]
