# Generated by Django 5.0.7 on 2024-08-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productinfo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='slug',
        ),
    ]
