# Generated by Django 5.0.7 on 2024-08-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_productinfo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='info',
        ),
        migrations.DeleteModel(
            name='ProductInfo',
        ),
    ]
