# Generated by Django 5.0.7 on 2024-08-22 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_info_delete_productinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='رنگ محصول')),
                ('size', models.CharField(max_length=100, verbose_name='سایز محصول')),
            ],
            options={
                'verbose_name': 'اطلاعات تکمیلی',
                'verbose_name_plural': 'لیست اطلاعات تکمیلی',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='products.productinfo', verbose_name='اطلاعات'),
        ),
    ]
